name: port-data-extraction
channels:
  - defaults
  - conda-forge
  - pyviz
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - cartopy
  - altair
  - vega_datasets
  - notebook
  - vega
  - seaborn
  - hvplot
  - geoviews
  - requests
  - census
  - selenium
  - beautifulsoup4
  - requests
  - geckodriver
#  - selenium-chromedriver
  - pip:
      - carto
      - pyrestcli
      - census_area
      - tweepy
      - textblob
